---
title: "R Notebook"
output: html_notebook
---

##Peer-graded Assignement: Getting and Cleaning Data Course Project
This repository is my submission for Getting and Cleaning Data course Project. It has instruction on how to clean data on a dataset

##Dataset
[Human activity recognition using Smartphones](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

##Files
    - Codebook.nb.html a codebook with explanation on all the variables used in the script, and any transformations of the dataset I performed
    - run_analysis.r script, performs the data prepation, which is then followed by cleaning the data as described in the course projects definition.
        1. Merges the training and the test sets to create one data set.
        2. Extracts only the measurements on the mean and standard deviation for each measurement. 
        3. Uses descriptive activity names to name the activities in the data set
        4. Appropriately labels the data set with descriptive variable names. 
        5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
    - FinalData.txt is the exported final cleand data set